-- DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS score;
DROP TABLE IF EXISTS setting;
DROP TABLE IF EXISTS battlelist;

-- CREATE TABLE user(
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--      TEXT UNIQUE NOT NULL,
--     password TEXT NOT NULL
-- );

CREATE TABLE player(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    gender TEXT(2) NOT NULL,
    org TEXT NOT NULL,
    phone TEXT(11) NOT NULL
);

CREATE TABLE score(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id INTEGER NOT NULL,
    round INTEGER NOT NULL,
    score INTEGER NOT NULL,
    against_score INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (player_id) REFERENCES player(id)
);

CREATE TABLE setting(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT,
    name TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL DEFAULT 'Not set yet',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE battlelist(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    round INTEGER NOT NULL,
    player_a INTEGER NOT NULL,
    player_b INTEGER NOT NULL,
    FOREIGN KEY (player_a) REFERENCES player(player_id),
    FOREIGN KEY (player_b) REFERENCES player(player_id)
);